### ISSUE TITLE
Add `devel` tag devcontainer

### ISSUE THREAD

**Issue by nick-robo** [rocker-org/devcontainer-images#38]
It would be great to have the devel version of R since there are going to be some breaking changes in the next release.

I've tried messing around with it myself to get it to build a container using `r-ver:devel` but I can't seem to get it to work.

**Comment by eitsupi** [comment]
Thank you for your interest in this project.

I think the issue is build frequency and demand.
I mean `rocker/r-ver:devel` is built daily, but CI in this repository does not build unless me (or other maintainers) run.
This means that the image built here will always be older than the latest devel version.

What we are doing here now is just installing two Dev Container Features, `ghcr.io/devcontainers/features/common-utils` and `ghcr.io/rocker-org/devcontainer-features/r-rig`, on top of `rocker/r-ver` etc., so we figure if users want to try the latest devel version they can build this themselves.

Where did you not do well with your build?

**Comment by nick-robo** [comment]
I think I just need to get more familiar with the docker/dev container syntax. Thanks for the explanation.
