### ISSUE TITLE
styler in devcontainer

### ISSUE THREAD

**Issue by sybrohee** [rocker-org/devcontainer-images#55]
Hello,

I would like to customize the format of the styler library that is used with my R devcontainer.

E.g. as shown https://github.com/REditorSupport/languageserver#customizing-formatting-style

However, I have no idea on where I should add this option so that it is taken into account by R when reformatting the code.

I already tried $R_HOME/etc/Rprofile.site (within the container) but it does not seem to be effective. It indeed modifies the content of the option languageserver.formatting_style but not the behaviour of the formatting.

Many thanks for your help and thank you for your amazing job with rocker and the dev-container.

**Comment by eitsupi** [comment]
I don't think that configuration is specific to devcontainer, so I suggest you ask the question in the languageserver repository rather than here.

Please check <https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf> about Rprofile.

**Comment by sybrohee** [comment]
Thank you for your kind answer and sorry to have bothered you with a question that was not directly linked to the devcontainer.
Regards.

**Comment by eitsupi** [comment]
Don't mind.
If you have any more questions, please feel free to open the issue. Thanks!
